version: "3.7"

services:
    database_test:
      image: postgres
      container_name: database_ignite_test
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=fin_api